#pragma once

#include <Arduino.h>

enum BootStage : uint8_t {
    BOOT_STAGE_NONE = 0,
    BOOT_STAGE_SERIAL_BEGIN,
    BOOT_STAGE_SERIAL_READY,
    BOOT_STAGE_CONFIG_BEGIN,
    BOOT_STAGE_CONFIG_READY,
    BOOT_STAGE_TRACE_READY,
    BOOT_STAGE_TFT_BEGIN,
    BOOT_STAGE_TFT_READY,
    BOOT_STAGE_WIFI_MODE_BEGIN,
    BOOT_STAGE_WIFI_MODE_READY,
    BOOT_STAGE_WIFI_MODE_FAILED,
    BOOT_STAGE_WIFI_MANAGER_BEGIN,
    BOOT_STAGE_STORED_WIFI_BEGIN,
    BOOT_STAGE_CAPTIVE_PORTAL_STARTED,
    BOOT_STAGE_CAPTIVE_PORTAL_INVALID,
    BOOT_STAGE_CAPTIVE_PORTAL_WEB_READY,
    BOOT_STAGE_WIFI_CONNECTED,
    BOOT_STAGE_WIFI_CONNECT_FAILED,
    BOOT_STAGE_NTP_BEGIN,
    BOOT_STAGE_NTP_READY,
    BOOT_STAGE_INITIAL_REST_BEGIN,
    BOOT_STAGE_INITIAL_REST_COMPLETE,
    BOOT_STAGE_WEBSOCKET_INIT_BEGIN,
    BOOT_STAGE_WEBSOCKET_INIT_READY,
    BOOT_STAGE_WEBSOCKET_CONNECT_BEGIN,
    BOOT_STAGE_WEBSOCKET_CONNECT_OPENED,
    BOOT_STAGE_WEBSOCKET_CONNECT_FAILED,
    BOOT_STAGE_WEB_UI_TASK_BEGIN,
    BOOT_STAGE_WEB_UI_TASK_READY,
    BOOT_STAGE_WEB_SERVER_BEGIN,
    BOOT_STAGE_WEB_SERVER_READY,
    BOOT_STAGE_MDNS_BEGIN,
    BOOT_STAGE_MDNS_READY,
    BOOT_STAGE_MDNS_FAILED,
    BOOT_STAGE_SETUP_COMPLETE,
    BOOT_STAGE_SETUP_ENTERED,
    BOOT_STAGE_TRACKING_READY,
    BOOT_STAGE_STATE_TRACE_BEGIN,
    BOOT_STAGE_WIFI_MANAGER_COMPLETE
};

void initializeBootStageTracking(unsigned long setupEnteredAt);
void enableBootStageSerialLogging();
void enableBootStageTraceLogging();
void markBootStage(BootStage stage);
const char* bootStageText(BootStage stage);
BootStage getCurrentBootStage();
BootStage getPreviousBootStage();
uint32_t getCurrentBootStageUptimeMs();
uint32_t getPreviousBootStageUptimeMs();
bool isBootStagePersistenceAvailable();
