#pragma once

#define FIRMWARE_VERSION "0.1.0-dev"

#ifndef __has_include
#define __has_include(header) 0
#endif

#if __has_include("GeneratedVersion.h")
#include "GeneratedVersion.h"
#else
#define GENERATED_GIT_HASH "unknown"
#define GENERATED_GIT_DIRTY 0
#define GENERATED_GIT_BRANCH "unknown"
#endif

#define FIRMWARE_GIT_HASH GENERATED_GIT_HASH
#define FIRMWARE_BUILD_DIRTY GENERATED_GIT_DIRTY
#define FIRMWARE_GIT_BRANCH GENERATED_GIT_BRANCH
#define FIRMWARE_BUILD_DATE __DATE__
#define FIRMWARE_BUILD_TIME __TIME__

#if FIRMWARE_BUILD_DIRTY
#define FIRMWARE_GIT_REVISION FIRMWARE_GIT_HASH "+"
#define FIRMWARE_BUILD_STATE "DIRTY"
#else
#define FIRMWARE_GIT_REVISION FIRMWARE_GIT_HASH
#define FIRMWARE_BUILD_STATE "CLEAN"
#endif

#define FIRMWARE_IDENTIFIER "FW " FIRMWARE_VERSION " / " FIRMWARE_GIT_REVISION
#define FIRMWARE_COMPACT_IDENTIFIER "FW" FIRMWARE_VERSION "/" FIRMWARE_GIT_REVISION
