$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$generatedHeader = Join-Path $repositoryRoot "GeneratedVersion.h"

function Invoke-GitValue {
    param([string[]]$Arguments)

    $result = & git -C $repositoryRoot @Arguments
    if ($LASTEXITCODE -ne 0) {
        if (Test-Path -LiteralPath $generatedHeader) {
            Remove-Item -LiteralPath $generatedHeader
        }
        throw "Git metadata generation failed: git $($Arguments -join ' ')"
    }

    return ($result | Out-String).Trim()
}

function ConvertTo-CString {
    param([string]$Value)

    return $Value.Replace("\", "\\").Replace('"', '\"')
}

$gitHash = Invoke-GitValue -Arguments @("rev-parse", "--short", "HEAD")
$gitBranch = Invoke-GitValue -Arguments @("rev-parse", "--abbrev-ref", "HEAD")
$gitStatus = @(& git -C $repositoryRoot status --porcelain)
if ($LASTEXITCODE -ne 0) {
    if (Test-Path -LiteralPath $generatedHeader) {
        Remove-Item -LiteralPath $generatedHeader
    }
    throw "Git metadata generation failed: git status --porcelain"
}

$dirtyFlag = if ($gitStatus.Count -gt 0) { 1 } else { 0 }
$content = @(
    "#pragma once"
    ""
    "// Generated by tools/build_prep.ps1. Do not edit or commit."
    "#define GENERATED_GIT_HASH `"$(ConvertTo-CString $gitHash)`""
    "#define GENERATED_GIT_DIRTY $dirtyFlag"
    "#define GENERATED_GIT_BRANCH `"$(ConvertTo-CString $gitBranch)`""
    ""
) -join "`n"

$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($generatedHeader, $content, $utf8WithoutBom)

Write-Host "GeneratedVersion.h: hash=$gitHash dirty=$dirtyFlag branch=$gitBranch"
